site_name: PYTQ
theme:
  name: readthedocs
  highlightjs: true
nav:
  - home: index.md
  - install: install.md
  - parameters: parameters.md
  - usage: usage.md
  - using the GUI: gui.md
  - pytq-manage: pytq-manage.md
  - specific configurations: specific.md
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - def_list
