site_name: PYTQ
theme:
  name: readthedocs
  highlightjs: true
nav:
  - home: index.md
  - install: install.md
  - parameters: parameters.md
  - usage: usage.md
  - using the GUI: gui.md
  - pytq-manage: pytq-manage.md
  - model and API: model.md
  - specific settings: specific.md
  - troubleshooting: troubleshoot.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: src
  - admonition
  - def_list

# pip requirements for mkdocs
# pip install mkdocs mkdocstrings mkdocstrings-python pygments==2.12 